import {
  AlertTriangle, Flower2, Heart, X, Sparkles, Mail, Wallet, Gift, MapPin,
  ArrowLeft, ArrowRight, Calendar, Plane, PartyPopper, Pencil, Music, Frown,
  Receipt, Lock, Trash2, CheckCircle2, Car, Clapperboard, Home, Container,
  Utensils, Coffee, Smile, LockKeyhole, MessageCircle, Check, Package,
  Palmtree, Smartphone, Banknote, ClipboardList, XCircle, Bell, Gamepad2,
  Moon, Cake, Gem, GraduationCap, Zap, Dumbbell, ShieldCheck, HeartHandshake,
  Leaf, Mic, CircleDot, PenLine, Users, Image, BarChart3, Camera, Laptop,
  Dog, TrendingUp, ShoppingBag, Droplet, Satellite, Flame, BookOpen, Shuffle,
  Dices, Meh, Angry, ArrowUp, ArrowDown, Search, Laugh, Sunrise, Bike, Bath,
  Palette, Pizza, Waves, Tent, Beer, Target, Briefcase, ShoppingCart, Inbox,
  FolderOpen, MailOpen, MailX, Music2, ScrollText, Lightbulb, Bookmark, Hand,
  Unlock, Globe, Mountain, Building2, Ship, Landmark, Map, Link2, Disc,
  Headphones, Ticket, Umbrella, DollarSign, TrendingDown, Hourglass, Cat, PawPrint,
  Undo2, Play, Pause, SkipForward, Hotel,
  type LucideIcon,
} from 'lucide-react';

// Every emoji still used as a raw glyph anywhere in the app maps to one
// Lucide icon here — this is the single place to add a new mapping instead
// of introducing another literal emoji character.
export const EMOJI_ICON_MAP: Record<string, LucideIcon> = {
  '⚠️': AlertTriangle, '⚠': AlertTriangle,
  '🌸': Flower2, '🌹': Flower2,
  '💕': Heart, '❤️': Heart, '❤': Heart, '💗': Heart, '🤍': Heart, '💖': Heart, '💙': Heart,
  '✕': X, '❌': XCircle,
  '✨': Sparkles, '✦': Sparkles, '🎆': Sparkles,
  '💌': Mail, '✉️': Mail, '✉': Mail, '📧': Mail,
  '💰': Wallet,
  '🎁': Gift, '🎀': Gift,
  '📍': MapPin,
  '←': ArrowLeft, '→': ArrowRight, '↑': ArrowUp, '↓': ArrowDown, '↩️': Undo2, '↩': Undo2,
  '▶️': Play, '▶': Play, '⏸️': Pause, '⏸': Pause, '⏭️': SkipForward, '⏭': SkipForward,
  '📅': Calendar,
  '✈️': Plane, '✈': Plane,
  '🎉': PartyPopper,
  '✏️': Pencil, '✏': Pencil, '📝': PenLine, '✍️': PenLine, '✍': PenLine,
  '🎵': Music, '🎼': Music2, '🎶': Music2, '♪': Music2, '🎸': Music, '🎹': Music,
  '🥺': Frown, '😭': Frown, '😴': Moon, '😤': Angry,
  '🧾': Receipt,
  '🔒': Lock, '🔐': LockKeyhole, '🔓': Unlock,
  '🗑️': Trash2, '🗑': Trash2,
  '✅': CheckCircle2, '✓': Check,
  '🚗': Car, '🚲': Bike, '🚢': Ship,
  '🎬': Clapperboard,
  '🏠': Home, '🏡': Home,
  '🫙': Container,
  '🍜': Utensils, '🍕': Pizza, '🍺': Beer,
  '☕': Coffee,
  '🥰': Heart, '😍': Smile, '😊': Smile, '😂': Laugh,
  '💭': MessageCircle, '💬': MessageCircle,
  '📦': Package,
  '🏖️': Palmtree, '🏖': Palmtree, '🏕️': Tent, '🏕': Tent, '🎪': Tent,
  '📱': Smartphone, '💻': Laptop,
  '💵': DollarSign, '💸': Banknote,
  '📋': ClipboardList,
  '🔔': Bell,
  '🎮': Gamepad2,
  '🌙': Moon,
  '🎂': Cake, '🧁': Cake,
  '💍': Gem,
  '🎓': GraduationCap,
  '⚡': Zap,
  '🏋️': Dumbbell, '🏋': Dumbbell,
  '🛡️': ShieldCheck, '🛡': ShieldCheck,
  '🫂': HeartHandshake, '💑': Users, '👥': Users,
  '🌿': Leaf, '🍂': Leaf,
  '🎤': Mic,
  '🎱': CircleDot, '🎡': CircleDot,
  '🖼️': Image, '🖼': Image, '📸': Camera, '📷': Camera,
  '📊': BarChart3, '📈': TrendingUp, '📉': TrendingDown,
  '💡': Lightbulb,
  '🐶': Dog, '🐱': Cat, '🐾': PawPrint,
  '🛍️': ShoppingBag, '🛍': ShoppingBag, '🛒': ShoppingCart,
  '💧': Droplet,
  '📡': Satellite,
  '🔥': Flame,
  '📖': BookOpen, '📜': ScrollText,
  '🔀': Shuffle,
  '🎲': Dices,
  '😐': Meh,
  '🔍': Search,
  '🌅': Sunrise,
  '🛁': Bath,
  '🎨': Palette,
  '🏊': Waves,
  '🎯': Target,
  '💼': Briefcase,
  '📥': Inbox, '📁': FolderOpen, '📬': MailOpen, '📭': MailX,
  '🔖': Bookmark,
  '👋': Hand,
  '🌏': Globe,
  '🗻': Mountain,
  '🌆': Building2,
  '🗼': Landmark, '🏯': Landmark,
  '🗺️': Map, '🗺': Map,
  '🔗': Link2,
  '💿': Disc,
  '🏨': Hotel,
  '🎧': Headphones,
  '🎟️': Ticket, '🎟': Ticket,
  '☂️': Umbrella, '☂': Umbrella,
  '⏳': Hourglass,
};
